name: whishapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.0-178.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  country_pickers: ^2.0.0
  flutter_hooks: ^0.18.1
  url_launcher: ^6.0.12
  path: ^1.8.0
  path_provider: ^2.0.6
  bot_toast: ^4.0.1
  mime: ^1.0.1
  open_file: ^3.2.1
  permission_handler: ^8.2.6
  share_plus: ^3.0.4
  photo_view: ^0.13.0
  intl: ^0.17.0
  flutter_svg: ^0.23.0+1
  video_thumbnail: ^0.4.3
  better_player: ^0.0.79

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
